name: maplibre_expressions
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1


environment:
  sdk: ^3.10.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.29.0
  very_good_analysis: ^10.1.0
